export const letters = [
  { letter: "A", ipa: "/eɪ/", guide: "Suena como «éi»" },
  { letter: "B", ipa: "/biː/", guide: "Suena como «bí»" },
  { letter: "C", ipa: "/siː/", guide: "Suena como «sí»" },
  { letter: "D", ipa: "/diː/", guide: "Suena como «dí»" },
  { letter: "E", ipa: "/iː/", guide: "Suena como «í»" },
  { letter: "F", ipa: "/ɛf/", guide: "Suena como «ef»" },
  { letter: "G", ipa: "/dʒiː/", guide: "yi" },
  { letter: "H", ipa: "/eɪtʃ/", guide: "eich" },
  { letter: "I", ipa: "/aɪ/", guide: "ai" },
  { letter: "J", ipa: "/dʒeɪ/", guide: "yei" },
  { letter: "K", ipa: "/keɪ/", guide: "kei" },
  { letter: "L", ipa: "/ɛl/", guide: "el" },
  { letter: "M", ipa: "/ɛm/", guide: "em" },
  { letter: "N", ipa: "/ɛn/", guide: "en" },
  { letter: "O", ipa: "/oʊ/", guide: "ou" },
  { letter: "P", ipa: "/piː/", guide: "pi" },
  { letter: "Q", ipa: "/kjuː/", guide: "kiu" },
  { letter: "R", ipa: "/ɑːr/", guide: "ar" },
  { letter: "S", ipa: "/ɛs/", guide: "es" },
  { letter: "T", ipa: "/tiː/", guide: "ti" },
  { letter: "U", ipa: "/juː/", guide: "iu" },
  { letter: "V", ipa: "/viː/", guide: "vi" },
  { letter: "W", ipa: "/ˈdʌbəl juː/", guide: "doble u" },
  { letter: "X", ipa: "/ɛks/", guide: "eks" },
  { letter: "Y", ipa: "/waɪ/", guide: "uai" },
  { letter: "Z", ipa: "/ziː/", guide: "zi" }
];